# Generated by Django 4.2.8 on 2024-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conform',
            name='username',
            field=models.CharField(default='default_username', max_length=250),
        ),
    ]
