# Generated by Django 4.2.8 on 2024-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_conform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conform',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
